
import type { Metadata } from "next";
import "./globals.css";
import { Bebas_Neue } from "next/font/google";
import { Toaster } from "@/components/ui/toast"

import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import Providers from "./providers";
export const metadata: Metadata = {
  title: "Domestic Travel",
  description: "Generated by create next app",
};
const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
});
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className={`min-h-full flex flex-col ${bebasNeue.variable}`}>
        <Providers>
          <Navbar />
          {children}
          <Toaster />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
